--CREATE GROUPS TABLE
DROP TABLE IF EXISTS [groups];
CREATE TABLE IF NOT EXISTS [groups] (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name STRING
);

--CREATE TEACHERS TABLE
DROP TABLE IF EXISTS teachers;
CREATE TABLE IF NOT EXISTS teachers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING
);

--CREATE STUDENTS TABLE
DROP TABLE IF EXISTS students;
CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING,
	group_id REFERENCES [groups] (id)
);

--CREATE SUBJECTS TABLE
DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name QNIQUE,
	teacher_id REFERENCES teachers (id)
); 

--CREATE GRADES TABLE
DROP TABLE IF EXISTS grades;
CREATE TABLE IF NOT EXISTS grades (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	subject_id REFERENCES subjects (id),
	student_id REFERENCES students (id),
	grade INTEGER,
	date_of DATE
); 
