# Generated by Django 4.2.1 on 2023-05-18 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0010_remove_quote_author_quote_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="authors",
            new_name="author",
        ),
    ]
