# Generated by Django 4.2.1 on 2023-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0012_alter_author_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(unique=True),
        ),
    ]
