"""Init

Revision ID: cd9dfacc340c
Revises: aed9f7df0c16
Create Date: 2023-04-27 14:42:26.381892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9dfacc340c'
down_revision = 'aed9f7df0c16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
