# Generated by Django 4.2.1 on 2023-05-17 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag_name",
            new_name="name",
        ),
    ]
