# Generated by Django 4.2.1 on 2023-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_rename_tag_name_tag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="name",
            new_name="fullname",
        ),
    ]
