# Generated by Django 4.2.1 on 2023-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0007_alter_quote_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="author",
        ),
        migrations.AddField(
            model_name="quote",
            name="author",
            field=models.ManyToManyField(to="quotes.author"),
        ),
    ]
