# Generated by Django 4.2.1 on 2023-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0013_alter_author_born_location_alter_author_fullname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="biography",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(),
        ),
    ]
